# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ejf8X9dpVQF3k6i-16KDC7HekNfPpq5y
"""

import pandas as pd
import random

# Existing data
baza = {
    "FISH": [
        "Muhammadjonov G'anisher", "Ketmonova Omina", "Teshayeva Maftuna",
        "Muhammadjonov Arrabek", "Turdiboyev Utirdibek", "Muhammadjonov Hadiyatullox",
        "Mamadaliyev Qozonbek", "Kabgiriyeva Omina"
    ],
    "Yoshi": [16, 15, 17, 16, 18, 15, 17, 16],
    "Jinsi": ["Erkak", "Ayol", "Ayol", "Erkak", "Erkak", "Erkak", "Erkak", "Ayol"],
    "qaysi maktab": ["Maktab 1", "Maktab 2", "Maktab 3", "Maktab 4", "Maktab 5", "Maktab 6", "Maktab 7", "Maktab 8"]
}

# Creating DataFrame
df = pd.DataFrame(baza)
print(df)
Filtir=df[(df["Yoshi"]==df["Yoshi"].min())]
print(Filtir)